---
title: "Leveraging Prediction Markets to Mitigate the Tragedy of the Commons Problem in International Climate Change Agreements"
date: 2020-04-16
tags: ["technocracy", "prediction markets", "school", "environmentalism", "futarchy"]
categories: ["society"]
description: "prediction markets applied to solving international agreements incentive problems"
draft: false
---
I wrote this paper as a course paper in sustainability and innovation at the University of Oslo. In the section before the conclusion I propose an original (possibly not, but I didn't find it elsewhere) system for coordinating government agreements around international policy.
** Abstract
Climate change presents a pressing range of tragedy of the commons problems, eg. global sea level and atmospheric carbon dioxide concentration. Barring the reduction of democracy to technocracy, there is a niche for innovation in the methodology employed by political bodies toward assessing solution quality and the probable outcome landscape of implementing a policy or resolution. Multilateral policy agendas coordinated between political actors represents one such opportunity. Attempts at collective action solutions often result in the emergence of tragedy-of-the-commons problems. I will analyze the tragedy-of-the-commons failure as pertaining to international climate summit resolutions, and introduce several implementations of prediction markets as a possible solution to the problems incumbent to global climate agreements, and tragedy-of-the-commons problems more generally.
** Introduction
Global climate summits an example of the tragedy-of-the-commons problem: political actors employ the ecopragmatist-originated sustainable transformation rhetoric as umbrage for resolution-reneging political failures, while the political incentive to meet international climate summit commitments is regularly outweighed by competing local political factors. Incentivizing multilateral follow-through on climate agreements requires addressing several sub-problems.
I will address and analyze the problems incumbent to the present system of climate resolution. Then I explore technocracy as a naive solution to the political problem of information aggregation. Then I will introduce prediction markets, applied to these problems in two possible implementations. Last, I will discuss some of the more common criticisms with prediction markets.
** Criticisms of the 2030 Agenda for Sustainable Development
The 2030 Agenda for Sustainable Development and SDGs [a], adopted in 2015 by the UN, outlines 17 goals and 169 targets for reducing poverty and engaging sustainable practices in participating nations. One might infer from the self-congratulatory language used on the website of the European Union that the Agenda’s success is all but assured: “the adoption of the 2030 Agenda was a landmark achievement, providing for a shared global vision towards sustainable development for all.” Claims to the contrary are in evidence.
425 days after the adoption of the Agenda (in 2016),  “tangible progress in terms of implementing the SDGs at the country level has been hard to come by” [c], and in the 2019 SDG report, United Nations Secretary-General António Guterres wrote “it is abundantly clear that a much deeper, faster and more ambitious response is needed to unleash the social and economic transformation needed to achieve our 2030 goals” [d].
One obvious problem is the excessive use of vague language in the agenda’s goals, eg. “3. Good Health and Well-Being for people– Ensure healthy lives and promote well-being for all at all ages”, in combination with ludicrously overzealous goals, eg. “1. No Poverty-End poverty in all its forms everywhere.” A child might have written these. For these among other reasons, the SDG goals were called “worse than useless” by The Economist in 2015 [b]. The document continues “All countries have a shared responsibility to achieve the SDGs.” To clarify: the term “shared responsibility” is political umbrage, indicative of no responsibility at all. Political leaders’ motives at summits such as these are not to acquire the relevant information, assemble coherent policy agendas, or otherwise solve any problems at all, but to author rhetorical nonsense, while pretending to be doing something.
A better system for aggregating the relevant information and constructing coherent policy agendas is in need. Before proposing an alternative, I analyze some of the problems inherent to the present system.
[a] https://ec.europa.eu/environment/sustainable-development/SDGs/index_en.htm
[b] https://www.economist.com/leaders/2015/03/26/the-169-commandments
[c] https://www.idea.int/sites/default/files/news/16-11-22-The_slumber_of_the_SDGs.pdf
[d] https://www.un.org/sustainabledevelopment/progress-report/
** Problems Inherent to International Policy Consensus
Three key problems emerge in the UN methodology in designing and implementing goals. The first has to do with the distributed nature of responsibility for implementing policy, resulting in a tragedy-of-the-commons problem. The second has to do with the existing processes by which existing information is aggregated into resolutions and policies. The last has to do with the reporting and accountability process, after resolutions and policies are put in place.
The distributed nature of responsibility among United Nations member nations decreases the degree of accountability any particular nation holds in following through on its commitments, eg. As member countries A and B commit to reducing it’s net carbon footprint, country B benefits from country A reducing its carbon footprint, but pays none of the costs incurred by decreasing country B’s own footprint. Thus country B has incentive to renege on its agreements while saddling country A with the costs. The scale of the problem increases with the number of countries, and their relative power differential. For instance, in our previous example, if country B is economically or militarily dependent on country A, country A has further less incentive to sacrifice immediate economic productivity to satisfy an international agreement. This puts weak nations in an impossible political situation, as Leichenko and Silva identify that “not only are the poorest and most marginalized disproportionately affected, but climate change impacts can also exacerbate existing inequalities” [e]. Note that country A may still enter an agreement with no intention of holding to it, so as to enjoy the benefits of other nations’ carbon footprint reduction while paying none of the costs. This provides context for how all 193 of the member countries of the United Nations committed to the SDG agenda, while funding for achieving these goals is 2.5 trillion dollars short of the 5 trillion per annum price tag [f]. The incentive to defect from agreements is a hallmark of the Tragedy-of-the-Commons problem. Holding to the international agreement is in direct competition with satisfying interest groups, promoting economic activity, and securing local objectives.
Solving tragedy-of-the-commons problems requires optimization in selecting realistically limited objectives, implementing effective policy to resolve those objectives, and measuring results.
Beginning with rational information acquisition, we may ask the question, how well informed with respect to realistic outcomes is current policy? Given that only 2 of the 17 SDG goals are currently on track, it seems safe to conclude: not very. This is a characteristic property of democracy: from the local to the international, voters have little chance to be pivotal in voting, irrational in selecting realistic policy paths, under-informed in policy relevant to them, and tribal in their ultimate policy preference.  Their representative politicians, responsible to their constituents, reflect these failures in information aggregation. In this system, relevant information for policy selection is regularly subverted to tribal preference, miscommunicated by media, deprioritized on the basis of technicality, or never brought to light in the first place. The result is the commitment toward ineffective and unrealistic solutions, as in the case of the 17 SDGs. As the power for humans to effect changes on our environment monotonically increases with time, political systems incorporating such failures as these doom the quality of our political decisions.
[e] https://onlinelibrary.wiley.com/doi/abs/10.1002/wcc.287
[f] https://www.nature.com/articles/d41586-019-03907-4
** Naive Solution: Technocracy
The most naive solution to the criticisms above, in particular with regards to climate action as a primarily scientific and economic domain of policy, would be to simply reduce the poIr of our representative democracy with respect to policy decisions inside certain domains, reallocating the poIr to shape policy to the set of experts perceived to be most relevant. Political systems in this arrangement are referred to as technocracies, and emerge commonly in businesses requiring technical expertise. Though a full analysis of the merits and weaknesses of technocracy is beyond the scope of this paper, a brief treatment of the most relevant problems of technocracy will prepare the ground for prediction markets.
Technocracy’s primary advantage in practice is an approximation of meritocracy flavored towards elevating the hierarchical importance of fact-based reasoning and technical ability to engage a somewhat predefined domain of technical problems.
The first problem in technocracy one might encounter is a problem with the very definition of what constitutes an “acceptable group of relevant experts.” Each word presents myriad problems. Acceptable to whom? Being acceptable to the public reduces our group of experts to little more than politicians. Being acceptable to other experts (if such a group even exists) exposes age bias, and is still vulnerable to a certain degree of politicking. Does relevant indicate the group should represent a sampling of interdisciplinary fields or should it be more constrained? Should the group’s participants be a dynamic set or a static one? What about overlapping expertise groups? This is to demonstrate that the problem of electing a set of experts in a democracy is quickly reduced to the problem electing politicians. Were it politically popular to elect expects, such would already be the status quo.
Even presupposing a mechanism for expert committee selection, a second class of political problem exists: technocracies are aristocracies with a chrome polish. That is, technocracies are closed political systems; once established, members of a technocracy could gate-keep even other experts out of the technocracy. This is acceptable in business, where gatekeeping takes the form of filtering new hires, but not in government, where a political near-invulnerability to criticism is unacceptable.
Finally, the problem domains in which technocracies thrive often allow for the opportunity for a posteriori improvements to solutions. Political environments are hostile to iterative policy change; that is, the cost of renegotiating policy decisions is high. Further, there are economic productivity losses in volatile policy environments. Thus policy technocracies are subject to the same constraint restriction of the existing democratic system: policy construction must optimally aggregate the available information landscape while navigating the political network. This implies that the information aggregation problem exists in isolation to the chosen political regime, suggesting that there may be better solutions to the problem of information aggregation with respect to the construction of policy decisions than resorting to a cabal of politically unaccountable domain experts.
Prediction Markets in Assessing Policy Directions
To my best knowledge, prediction markets were introduced as having potential as a democratic process by economist Robert Hanson [g]. Hanson proposed that “inferior policies happen because our info institutions fail to induce people to acquire and share relevant info with properly-motivated decision makers.” Hanson identified inferior processes for generating and evaluating information relevant to governing as responsible for economic divergence between democracies, and proposed prediction markets as a solution. Prediction markets are effective at aggregating information about the probable outcomes of a proposed action. By their application to policy, nations may optimize policy selection, while resolving an incentive mechanism to counteract the tragedy-of-the-commons problem. Note that the ability of prediction markets is limited to expressing probable outcomes of policy alternatives, not in expressing what outcomes are qualitatively better than one another.
Participants in a prediction market bet on the outcome of a particular event by an agreed upon point in time. For example, suppose at time t=0, a prediction market opens around whether policy A will achieve event Z by time t=T. Bettor 0 believes the outcome is likely, and bets $70. Then at time t=1, bettor 1 believes the outcome is only 70% likely to occur, so bettor 5 bets $30 against. The betting market now reflects a 70% chance of action success. If no further bettors enter, and the result is positive, the first seven bettors split the $30 counterbet, and if the result is negative, bettor 1 takes the $70. But now suppose an alleged domain expert, bettor 2, sees the 70% betting odds, and thinks the odds are much closer to 40%. If bettor 2 is correct, he will profit off of making any bet moving the odds closer to 40%. He does so by betting $75 against. The prediction market thereby incentivizes all domain experts, regardless of credentialing, to apply their knowledge for the public interest. This system avoids the closed property of technocracies’ only allowing for the expressed opinions of a narrow, preselected group of experts, while simultaneously allowing for democracy to take place around the most engaged, informed, and affected constituents. Statistics reflect this: in one study, prediction markets around elections were found to be 74% more effective than polling over 964 elections, with an even greater advantage in forecasts beyond 100 days [h].
In the context of policy selection, a political committee could propose several policy alternatives to a betting market in reference to their ability to achieve some outcome.  After some waiting period (requiring some mechanism to avoid allowing last minute interference bets), the committee could then implement the policy alternative seen as most likely to succeed, and reset all markets of policy alternatives not taken.
One of the most common criticisms of prediction markets as a vector to inform policy decisions is the opportunity for interest groups to tip the scale by betting overwhelmingly in their preferred direction. But placing restrictions on the maximum bet should not be necessary. The event of an interest group betting tremendously in one direction should be seen as a tremendous arbitrage opportunity for prediction market participants, as the interest group is not strictly buying “votes” per se, but expressing an opinion concerning the likelihood of an outcome. For instance, if a petroleum company sought to sabotage a prediction market around the probability that policy A achieves outcome Z by betting overwhelmingly that an alternative policy B achieves outcome Z better than policy A, bettors are incentivized to take the counter-bet of petroleum company on policy B, reaping an arbitrage opportunity. This is because bets are not votes: votes are expressions of preference (which deserve discussion in a paper in their own right), bets are expressions of belief about the state of the world, and the consequences of a given action.
[g] http://mason.gmu.edu/~rhanson/futarchy2013.pdf
[h] https://www.sciencedirect.com/science/article/abs/pii/S0169207008000320
** Prediction Markets as Staking Mechanisms
Bets are mechanisms for forcing alignment between beliefs and actions. Among the problems inherent to the tragedy-of-the-commons is that actors are incentivized to lie about intentions, or to otherwise express under-calibrated opinions. In addition to their role in information aggregation, prediction markets can serve a mechanism for constructing stake in international policy agreements.
A staking mechanism is a procedure in which a participating party accept some quantity of risk, for one or more of the following purposes: (i) as collateral against the party to breaking agreements, (ii) as a signaling mechanism intended to encourage further action by other parties, ie. the public, (iii) as a substitute for, or complement to reputation, in systems where reputation is insufficient in one of the two above ways, (iv) as a bet on a particular outcome with some probability and expectation of returns with positive expected value (v) from the perspective of an observer to the staking process, a mechanism for collecting information about the belief state of participants in the staking system. All but definition (iv) are directly relevant to the discussion of inducing actors to commit to and engage in a more desirable set of actions, in particular, with respect to preserving the environment among other desirable outcomes.
A proposed system for international politics could proceed as follows: First, a desired outcome is determined, for instance, a k% reduction in carbon footprint by each nation within 3 years, where each nation gets to choose their value for k, but exponentially increasing upfront costs to a nation’s choice of k below some value. Nations would be required to bet some minimum percentage of their GDP as stake toward meeting their target. Finally, delegates from each nation would proceed to place bets on each other nation’s objective being met with and against that nation’s staked bet.
This system has several advantages. First, it avoids a one-size-fits-all problem of international politics: policy that is effective or reasonable in one nation may not at all be in another. By calibrating goals with respect to each nation, we avoid the problems inherent to the SDG goals’ being simultaneously vague and exaggerated.
Second, if nation A’s delegates bet that nation B succeeds at meeting its policy goal, nation A is incentivized to pressure and assist nation B in meeting that policy goal, fostering international cooperation, rather than creating opportunity for defection from agenda agreements.
Third, the process creates a reasonably interesting opportunity for popular engagement in international politics. An international betting market between nations would be the international policy equivalent of the Olympics, and would likely draw a great deal of popular attention, raising the stakes for failing to meet commitments.
** Conclusion
I have analyzed several problems with the international political process, embodied in the 2015 SDGs, and proposed two possible implementations of prediction markets as solutions for rationally aggregating information. I introduced technocracy as a toy solution to better information aggregation, and explored the undesirable properties inherent to that solution as an alternative for eliminating the irrationality inherent to democratic processes. I aimed to attempt to solve the tragedy-of-the-commons problem emergent in international politics, while identifying the economic mechanism failures of the existing process.


** Bibliography
Berg, J. E., Nelson, F. D., & Rietz, T. A. (2008, April 28). Prediction market accuracy in the long run. Retrieved from https://www.sciencedirect.com/science/article/abs/pii/S0169207008000320
Get the Sustainable Development Goals back on track. (2020, January 1). Retrieved from https://www.nature.com/articles/d41586-019-03907-4
Hanson, R. (n.d.). Shall We Vote on Values, But Bet on Beliefs? Retrieved from http://mason.gmu.edu/~rhanson/futarchy2013.pdf
Leichenko, R., & Silva, J. A. (2014, May 2). Climate change and poverty: vulnerability, impacts, and alleviation strategies. Retrieved from https://onlinelibrary.wiley.com/doi/abs/10.1002/wcc.287
Sustainable Development Goals Report - United Nations Sustainable Development. (n.d.). Retrieved from https://www.un.org/sustainabledevelopment/progress-report/
The 169 commandments. (2015, March 26). Retrieved from https://www.economist.com/leaders/2015/03/26/the-169-commandments
The 2030 Agenda for Sustainable Development and the SDGs. (n.d.). Retrieved from https://ec.europa.eu/environment/sustainable-development/SDGs/index_en.htm
Vandemoortele, J. (2016, November 22). How to bring the SDGs out of their current slumber? Retrieved from https://www.idea.int/sites/default/files/news/16-11-22-The_slumber_of_the_SDGs.pdf
