---
title: "Review of Ai Superpowers: China, Silicon Valley, and the New World Order, by Kai Fu Lee"
date: 2020-01-26
draft: false
tags: ["ai", "tech", "china", "book"]
categories: ["book"]
---

* Review
Rating: 7/10* (9/10 for the first six chapters)

AI Superpowers is an China-optimistic perspective from a Chinese
venture capitalist on the state of advancing competition between China and the
rest of the world, which one might (understandably) believe was only Silicon
Valley after having read this book. In the first several chapters, Lee sets up a
framework to defend his optimism for Chinese firms potential to compete in
artificial intelligence by contrasting Chinese entrepreneurial culture to
Silicon Valley’s, and drawing stark contrasts between American and Chinese
governments approaches to their respective technology industries. Some of Lee’s
claims require scrutiny, including his bolstering for Chinese government,
borderline-advocacy of ruthless business practice, and characterization that
Silicon Valley is pitting elite researchers against Chinese good-enough
engineers. However, the book is an invaluable resource for anyone seeking to
gain better understanding of how entrepreneurship operates in China, and how the
rising Chinese technology economy may overwhelm expectations as an unprecedented
powerhouse in emerging technology areas. My interest I suspect the emergence of China as a
technological superpower bodes ill as a spectre of things to come with regards
to the Chinese reputation of undermining humanism and political freedoms.

Lee’s deconstruction of AI as a field is most comprehensive in the middle of the
book. Lee gives a careful analysis of the four application “waves” of Artificial
Intelligence, in considering those that Chinese firms will be most competitive
in. He weighs questions about “grid” versus “battery” approaches to artificial
intelligence. Championing for the Chinese government’s inefficient, yet clear,
approach to stimulating growth with massive incentives, and invasive data
collection practices, Lee’s analyses are sometimes poetic, but always
optimistic.

In the last half of the book, Lee (rather abruptly) changes topic. His close
encounter with cancer drives him to climb a mountain, to talk to a monk, to
celebrate a volunteer golf cart driver, and finally present his thesis on how AI
tech has the capacity to displace whole societies. His last two chapters
describe what we as a society might do to limit the negative consequences of
what will be gradual but massive displacement and unemployment. Though I'm
persuaded that society will undergo a massive displacement, Lee's newfound
enlightenment in how to reorganize a post-work society were underwhelming at
best, or as I feel is more likely, merely insincere poetry. He proposes a new
culture code for society, around the principles of human love, service, and
compassion, over present imperatives to find productivity. His transformation
story, both for himself and for society land a bit clumsily: his personal
transformation from human-turned-work-algorithm to friend and teacher read as an
abrupt turn: an out of place single chapter in the book.

By the end of the book, I felt I had a plausible and detailed thesis for how
Chinese entrepreneurs might compete with their American counterparts. I
understood the advantages that Chinese businesses wield, and the role the
Chinese culture and government may play in that transition. The latter half of
the book read more clumsily. Lee’s arguments for how we may transform society to
avoid dramatic social upheaval were well considered, though less insightful, and
more castle-in-the-sky than his exposition on the Chinese technology story.

* Rating
First half (6 chapters): information dense enough for a 9/10.

Second half: often off topic, with a cancer story, an underdeveloped thesis for
post-work social change, punctuated with emotionally disingenuous personal
anecdotes. 5/10

Total: 7/10
