---
title: "Human Rights: Entertaining the Illusion"
date: 2019-12-10
tags: ["human rights", "history", "school", "politics"]
categories: ["society"]
description: "a pessimistic insistance on honesty in the story of human
rights history"
draft: false
---


** Introduction
“The speed with which human rights has penetrated every corner of the globe is astounding. Compared to human rights, no other system of universal values has spread so far so fast…. In what amounts to a historical blink of the eye, the idea of human rights has become the lingua franca of international morality” (Normand 8). With the simultaneous rise of secularism and the middle class in colonial Europe in the 19th Century, so rose the need for the decoupling of moral justifications for imperialism from religious precedents. Human rights left the sacred behind as a construction of universal humanist norms, to inspire the support of a rising middle class in a modernizing Europe. By donning the vestiges of moral supremacy, Europeans gained new justification for civilizing, educating, and employing the next century of colonial labor, while stemming criticisms of the rising bourgeois class. Human rights have always been a farce, and they remain expensive moral umbrage for nations and the elite.

The International Criminal Court, established in 2002, took ten years before its first successful prosecution, of Congolese warlord Thomas Lubanga Dyilo. The cost of the ICC, in the first 10 years, exceeds 1 billion dollars. The major international criminal courts in aggregate exceed 6 billion dollars (Stuart 968). The United States, on whom much of the funding and legitimacy for international human rights relies, maintains immunity for its citizens by the 2002 American Service Members’ Protection Act. The rise of political rivals, most prominently Brazil, Russia, India, China, and South Africa, to American and European power, present a valid challenge to the underlying assumption embedded in the most basic premise of human rights: can human rights be truly universal, or are these simply the last vestiges of the once religious, now secular, hypocrite phoenix of moral supremacy? In an examination of the accomplishments of human rights through four eras, I’ll attempt to disentangle the self-aggrandizing mythos of human rights from reality.

Ford, S. “How Leadership in International Criminal Law is Shifting from the U.S. to Europe and Asia: An Analysis of Spending on Contributions to International Criminal Courts (2011). Saint Louis University Law Journal, Vol. 55, p. 953.
Normand, R., Zaidi, S. “Human Rights at the UN: The Political History of Universal Justice” (2008). Bloomington: Indiana University Press.

** 1776-1947: Era of The Bourgeoisie, Secularism, and Capitalism
The modern age of human rights very little resembles its prehistory. Democracies and autocracies, including monarchies, have vastly different requirements of their populations and legal frameworks. Democracies are held to higher standards of justification for political action. The overthrow of European monarchs marks one of the more productive eras in de-facto human rights development, though the language of human rights is mostly a post World War II invention.

While difficult to quantify, one can reasonably hypothesize that the great advances of this era in human rights is the product of the success of popular uprisings, and the initial successes of expanding democracy, and its deceleration in the 20th century represents conflict of haves and have-nots: wealthy democratic countries have no more incentive than wealthy autocratic ones to preserve the human rights of other nations, especially when these rights conflict with at-home economic interests.

At the beginnings of the Age of Exploration, beginning with Portueguese navigators in the 15th and 16th Century, monarchs had little need of moral justification towards the end colonizing and enslaving. In the twin, unrivaled power structures of church and state, were generally sufficient justifications for expansion of empire in the name of God and country.  But the trappings of exploration produced rivals to the landed elite: the bourgeoisie, in whom the elites invested.

The British, with far-flung colonies and powerful shipping merchants bore witness to this. The Declaration of Independence, penned by American plantation owner Thomas Jefferson, is the product of the realization by American bourgeoisie that they possess sufficient wealth to contest, and even field armies against traditional monarchical power. Jefferson couches protestations towards monarchal Europe in proto-human rights declarations of offenses by the crown, violating “certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.” The American Constitution re-affirms and cements the political rights of American citizens in The Bill of Rights albeit, excluding most of the population.

Two decades later, revolutionaries in France mirror the American uprising, and take advantage of the financially drained Louis XVI to declare their rights as justification for revolution in The French Declaration of the Rights of Man. The age of the bourgeoisie, while still exclusionary to the vast majority of citizens, makes the beginnings of human rights discussion possible. But by this point in history, rights are not declared by top-down organizations and governments, but are the product of bottom-up uprisings.

The year 1848, known as the Spring of Nations, brought a wave of popular uprisings across over 50 countries in Europe (Evans). The revolutions mostly aimed to overthrow monarchical power, while demanding democracy, freedom for the press, and rights for the working class. These rebellions were mostly secular: religious leaders traditionally worked in concert with monarchs suppress challenges to existing power structures. The revolutions succeeded to varying degrees at establishing democracies, but the agitation for a definitive set of rights, was impossible for elites to ignore. European humanist norms grew out of the revolutions, supporting the rights of the newly established bourgeois.

These rights would come under assault in the first half of the 20th Century. The twin cataclysms of the World Wars reduced Western Europe to rubble, allowing the advancing American economy to surpass its European forebears. The devastating effects of the world wars also propelled the advance of democracy and capitalism in Western Europe, and communist dictatorship in Eastern Europe. The positive narrative identifies this struggle as that of competing ideologies in a brawl of how best to assert the political and social rights against a Hobbsian struggle of all against all. The remaining powers needed new language to justify the shattered myths of the previous century, asserting that humanist rights existed, and could not be abused at any time by the existing power structures, as they had been in the world wars.

It’s worth noting that each of the participants in the Second World War abused and repressed citizens in a major way. Though this list is hardly exhaustive: Jim Crow in the United States, colonial oppression by Western Powers, barbaric war crimes by the Japanese, and genocides by Nazis and Soviets. These were the powers submitting diplomats to pen the first modern document of Human Rights, the Universal Declaration of Human Rights (UDHR). This stands in sharp contrast to the emergence of rights following popular uprisings in the 18th and 19th Centuries.



R.J.W. Evans and Hartmut Pogge von Strandmann, eds., The Revolutions in Europe 1848–1849 (2000) pp. v, 4

Declaration of Independence, Paragraph 2 (1776).



** 1947-1976: Era of The Universal Declaration of Human Rights

In the aftermath of the Second World war, world leaders gathered in Paris to pen the UDHR. According to international law professor Stephen Hopgood in The Endtimes of Human Rights, the UDHR was “an antidote to a troubling contradiction, the coexistence of progress with intensifying violence, vast social and economic inequality, and fears of “the disenchantment of the world” (Hopgood 1).

The modern language of human rights was borne out of the need for a neutral and secular ideology for developed nations to use as a neutered critique of one another, to limit risk of a third world war. European and American leaders sought to weave into the UDHR an ideological alibi for a new globalized economic system designed to promote international collaboration, benefitting the elites, while only supporting an enhanced sentimentality for human rights in tongue. The UDHR, therefore was a set of thirty non-binding articles, agreed upon by world leaders, but not to be taken seriously. Economist Eric Posner writes in The Twilight of Human Rights “the words in the Universal Declaration may have been stirring, but no one believed at the time that they portended a major change in the way international relations would be conducted, nor did they capture the imagination of voters, politicians, intellectuals, leaders of political movements, or anyone else who might have exerted political pressure on governments” (Posner 17).

Why were the articles non-binding? The authors of the UDHR were not the surviving revolutionaries seeking to validate the rights of humans against their former governments, but the ambassadors of the most powerful nations, who sought to reaffirm their hegemonic power by a set of tacit agreements to not challenge one another militarily. These diplomats were not defending human rights in the sense that human rights protect people from their governments: they were protecting their nations, developed nations, from the threat of war. Any illusion of possible agreement concerning universal ideals was quickly dispelled: there were clashes between the United States diplomat, Elanor Roosevelt, with the Soviets concerning rights to property and political freedoms, opposition by the Saudis towards articles concerning freedom of religion, Latin American diplomats who wanted God mentioned, and fears of colonial intervention by the British and French, while the Japanese were to be stripped of their recent colonial acquisitions (Loeffler).

The effects of the UDHR on human rights around the world were underwhelming. The United Nations established a commission for responding to human rights complaints. In the first ten years of operation, roughly 65,000 letters alleging human rights violations arrived at this newly minted defender of human rights. The commission declined to investigate a single complaint (Loeffler). Issues emerged as larger powers did not want to risk upsetting the power balance between the Soviet Union and the United States, potentially triggering war, and smaller powers had neither the political capital, resources, nor incentive to begin investigations. The UDHR proved an empty set of nice sounding words. This was not unexpected, even at the outset: according to international law expert Hersch Laueterpacht in 1947, “to a lawyer, the enunciation of a right without the provision of a remedy is a judicial heresy…It is clear to me that the declaration does not carry things further and that in some important respects has put the clock back.” (Loeffler)


Loeffler, J. (2018, December 21) “Human rights treaties promised a better future. Why did they fail?”. Washington Post.
Hopgood, S. (2015). The Endtimes of Human Rights. Ithaca: Cornell University Press.
Posner, E. (2014). Twilight of Human Rights Law. Oxford University Press.


** 1976-1991: Era of Human Rights Treaty Proliferation and American Money

The modern age of human rights organizations begins in earnest in the 1970s with the International Covenant on Economic, Social and Cultural Rights (ICESCR) and the International Covenant on Civil and Political Rights (Moyn). The covenants were intended as an expansion of the UDHR, but this time, gave overseeing commissions more power to enforce violations. The covenants were contemplated as early as 1948, by American historian Arthur Holcombe, as “a project for a piece of international legislation, more ambitious and perhaps more important than any other in the history of international law. If supported by suitable measures of implementation, it could be a great triumph of reason over force and violence in the development of human relations.” (Holcombe, 413)

Thus, the 1970s represent the shifting tide of human rights from general irrelevance to a proliferation of human rights treaties, to mixed effect. Some of these genuinely treated human rights issues, ie. Convention on the Elimination of Discrimination Against Women (CEDAW), while others were microcosms of the symbolic battles between the United States and the Soviet Union. The United States used human rights law as political leverage against the Soviet Union, while in exchange for ideological concessions, the Soviets bought recognition of autonomy in determining the freedoms of Eastern Europe.

The beginnings of American involvement in human rights in the 1970’s signaled the end of a unipolar European human rights era, though for a time human rights became unipolar about the American-centric perspectives, a phenomena that strengthened after the collapse of the Soviet Union, and has only in the last decade seen significant challenges by economic competitors to the United states, most prominently China. The era of American influence saw the demise of what Hopgood describes as European “secular religiosity” and towards the American style of political intervention in the name of defending democracy—where democracy was a thinly veiled stand-in for American economic interests.  Recent examples include American ongoing relations with Saudi Arabia, 1990s support Saddam Hussain in Iraq, and strategic support of torture in Guantanamo Bay.

The Americans, even under the most ardent human rights supporter, President Carter, were inconsistent allies to the human rights endeavor: “human-rights violating allies like Iran and Saudi Arabia were just too important for American security, and seen as an important counterweight to Soviet influence, so Carter could not consistently follow through on his rhetoric by threatening to withhold diplomatic support or economic resources from some of the worst violators of human rights” (Posner 18). While the United States generally supported and provided funding for major human rights organizations, they seldom ratified human rights treaties, and only with a raft of Reservations, Understandings, and Declarations (RUDs) limiting the United States’ liability to upholding the treaty.

Not that this was likely even necessary. Many authoritarian countries ratified the ICCPR, and other human rights treaties, and although these treaties were designed to be more binding, the same issue of political non-incentive for any particular country to take action resurfaced. Further, the treaties often used vague, sometimes self-negating language, or specified requirements that would be aspirational for all but the richest countries. Article 19 of the ICCPR declares the right to freedom of expression, but in the next paragraph, offers governments a get-out clause:

2. Everyone shall have the right to freedom of expression; this right shall include freedom to seek, receive and impart information and ideas of all kinds, regardless of frontiers, either orally, in writing or in print, in the form of art, or through any other media of his choice.
3. The exercise of the rights provided for in paragraph 2 of this article carries with it special duties and responsibilities. It may therefore be subject to certain restrictions, but these shall only be such as are provided by law and are necessary: (a) For respect of the rights or reputations of others; (b) For the protection of national security or of public order (ordre public), or of public health or morals.

The gates of plausible deniability in the clause, “protection of national security or of public order.. or morals,” swing wide. The failings of the covenants were appreciated at the time. Pakistani legal scholar, Hamid Kizilbash wrote of the covenants in 1976 that “what is most unsatisfactory about the implementation procedure is the fact that the individual has no role in the preparation of reports. States are not called upon to consult or transmit what an individual group within their territory may wish to have included in the report. No system of hearings, public consultation and individual petitions has been provided for. In the absence of such provisions it is clear that the reports will reflect whatever the government of a state wishes to make known” (Kizilbash 57).

Holcombe, A.N. "The Covenants on Human Rights", Law and Contemporary Problems, 14 (Summer 1948), pp. 413-429.
International Covenant on Civil and Political Rights, Article 19 (1966).
Kizilbash, H. “United Nations and Human Rights: A Failure Report” (1974). Pakistan Horizon Vol. 27, No. 1 (First Quarter, 1974), pp. 50-60
Moyn, S. (2010). The Last Utopia. Harvard University Press.


** 1991-now: Era of American Pseudo-Unipolarity
In the wake of the fall of the Soviet Union, one might reasonably assume a raft of advances human rights could proceed, over the corpse of their most powerful political opponent. However, immediately following the fall of the Soviet Union, events made a mockery of such an assumption. First, the horrifying genocide in Rwanda, where more than 800,000 Tutsis were slaughtered by the Hutu majority in Rwanda (Posner). The event was made for macabre spectator sport for the human rights organizations of Europe, demonstrating the irrelevance of the now nearly 50 year old Convention on the Prevention and Punishment of the Crime of Genocide and the commission appointed to advise the UN. The lesson repeated itself one year later in the civil war in Yugoslavia where Serbians attempted to ethnically cleanse Bosnians from the region, shocking Europeans to see genocide return once more in the 20th Century to their own continent.

The war criminal trials that followed (the UN was basically immobile during the atrocities) were widely criticized for bias and inconsistency, leading to the establishment of the International Criminal Court in 1998, and official opening in 2002. It has tried few, successfully tried fewer, and those it has tried are exclusively from African nations. The court took 10 years before its first successful prosecution, of the Congolese warlord Thomas Lubanga Dyilo. It is also expensive, costing a billion dollars in its first decade.  The United States continues to claim immunity to the court, and refuses to provide funding for the court. Naturally, the court appears mostly irrelevant.

According to Freedom House, every year since 2005 has seen a retreat in democracy and an advance of authoritarianism. Modern democracy has seen a corresponding retreat of the notion of the public space where facts exist as universal. Propaganda experts in Russia successfully used data, with the aid of data company Cambridge Analytica to spread disinformation about political events in the United States and the United Kingdom leading up to the 2016 election, and the Brexit referendum. Facebook has set new norms for the public dialogue between fiction and fact, allowing disinformation to be spread, while making surveillance easier than ever before (Snyder). Democracy has succumbed to populism in Hungary, Poland, Brazil, and Bosnia in the last decade. Human rights efforts, by contrast, appear to be stuck in the 19th century.

In 2017 the Office of the High Commissioner for Human Rights launched their 70th year anniversary campaign. The campaign feature the hashtag, #standup4humanrights, along with a website proclaiming “we can all be Human Rights Champions.” The website encouraged participants to post stories online, on platforms including Snapchat, Instagram, and yes, Facebook, the last of whom there has received no official comment on, or criticism of, by any of the human rights commissions at the UN. “All it takes, apparently, is posting individual stories online and recording an article of the declaration in one’s own language. There is hardly any mention of law or politics; it suffices to ‘promote, engage and reflect.’” (Loeffler)

Snyder, T. (May 21, 2018) “Facism is back. Blame the Internet.” Washington Post.

** Conclusion
Throughout this essay, I’ve alluded to the differences between revolutionaries’ claims to rights, and governments’ self-justification via an invented language of international law. Hopgood explains the difference between top-down human and bottom-up human rights as follows, “the local and transnational network of activists who bring publicity to abuses they and their communities face and who try to exert pressure on governments and the United Nations for action, often at tremendous personal cost”, versus “a global structure of laws, courts, norms, organizations that raise money, write reports, run international campaigns, open local offices, lobby governments, and claim to speak with singular authority in the name of humanity as a whole” (Hopgood 2). The criticism reflects the conflict of liberal versus the libertarian, in the question, does greater bureaucracy correspond to gains in human potential, or is the growth that of a cancer, whose purpose is not to serve the body out of which it was conceived, but only to grow?

This central conflict plays out while human rights activists engage bottom-up, grassroots endeavors around the world. These countries lie beyond the political purview of the International Criminal Court in the Hague, struggling against the rise of tyranny and nationalism in places like Bolivia, Venezuela, China, and Russia. Resistance movements can only seldom rely on the international bureaucracy to provide the assistance promised in lofty covenants. If human rights organizations had any legitimate influence, the Arab Spring would have been unnecessary, and dictators in Egypt and Syria would have been replaced by human rights leaders. Instead, politicians in countries like the United States and Russia used human rights declarations as pawns to maintain economic interests in the region.

What is unconscionable is that human rights organizations continue to ignore criticism of the failings of the movement. Foreign policy analyst David Rieff wrote of this phenomenon of cognitive dissonance, “This is predictable. If your expectations are millenarian — if you believe there is a right side of history, yours, and a wrong side of history that is doomed to defeat — skepticism about the human rights project, let alone voices of opposition, is unlikely to sway your position” (Rieff). Human rights activists need to justify the unmerited and costly expansion of their bureaucracies. Human rights documents need to have more substantial teeth than the possibility that a commission will enter into dialogue with a violating nation. The failures of human rights organizations are costly not only in price but in their deception: allowing nations to do the bare minimum to defend democracy and free people around the world.


Rieff, E. “The End of Human Rights?” (April 9, 2018). Foreign Policy Magazine.
