---
title: "NFT Hype"
date: 2021-03-26T12:16:49+01:00
draft: false
tags: ["nft", "crypto", "predictions"]
categories: ["crypto"]
---

/first posted at the [[https://medium.com/zeroknowledge/zero-knowledge-the-game-688ec3709b41][ZKPodcast blog]]/

** What's That?
#+begin_verse
"What's that?" Anna asked.
"It's anything you want it to be," said Ted the Tokenmaker.
"But that's not a thing," said Anna.
"That's the magic of crypto," said Olly the Optimist, "the more people believe
in these, the more they are."
...
"What's that?" said Alex.
"It's anything you want it to be," said Anna.
"Sounds like magic beans," said Alex.
"They are until they're not, unless they are, but I like them so who cares?" said Anna.
#+end_verse

This article responds to the [[https://medium.com/zeroknowledge/nfts-so-hot-but-would-you-buy-one-31fe280d7cb7][thoughtful piece]] by Anna Rose, which is recommended
pre-reading, as this piece will attempt to respond to the posed questions:
What exactly are NFTs for, and what would make me buy an NFT?

How to price NFTs is beyond the scope of this article, but I recommend [[https://medium.com/@nic__carter/why-nfts-are-hard-to-explain-48f0ab0a35bf][Nic Carter]] and
[[https://newsletter.banklesshq.com/p/how-to-value-nfts][William Peaster]] for some useful takes.

** What are NFTs for, and Why you might want one
Much of the noise around NFTs stems from the question, what the hell am I going
to do with this? An NFT is a sufficiently general technology that, in theory,
there are [[https://twitter.com/jbrukh/status/1367471632932085760][many]] uses for NFTs; yet in practice, art and gaming have attracted the
greatest share of attention. Looming behind these is the spectre of rampant
price speculation, divorcing many NFT products from any semblance of intuitive
valuations. At its [[https://www.theverge.com/2021/3/11/22325054/beeple-christies-nft-sale-cost-everydays-69-million][highest echelons]], the NFT investment game is being played by
[[https://cryptounit.com/2021/01/25/flamingodao-acquires-cryptopunk-nft-for-761k-in-ether/][DAOs]] and whales playing a game of chicken, taking turns in bidding increasingly
unbelievable amounts, in turn raising the overall value of their impressive
collections (which may then be quietly sold for a [[https://twitter.com/pranksyNFT/status/1366589669568360457][tidy profit]]).

NFTs aren't just for speculation. They're also for status signalling, as [[https://medium.com/@nic__carter/why-nfts-are-hard-to-explain-48f0ab0a35bf][Nic
Carter]] of Castle Island Ventures points out:
#+begin_quote
Most likely, I’m betting that newly-rich Ethereum enthusiasts will see the NFTs
as a kind of totem of status, signalling membership in an exclusive club (people
that had the foresight to buy the first NFTs on Ethereum, or the financial clout
to buy them once they got popular.) My best thesis here is that these are
effectively a form of resalable social signalling, like a digital Hermes Birkin
bag. The actual contents of the NFT is largely irrelevant.
#+end_quote

We see this playing out on Crypto Twitter, where [[https://www.larvalabs.com/cryptopunks][CryptoPunks]] and [[https://mooncatrescue.com/][MoonCats]] are
becoming increasingly common avatars for prominent crypto community members.
Paying the exorbitant price to acquire one of these cements one's identity as a
crypto OG, or at least as a community member willing to pay for their status.

Finally though art NFT prices are wild, prices go to supporting artists and
artist communities (assuming you're not being duped into [[https://cryptobriefing.com/crypto-art-fraud-rarible-sparks-governance-discussion/][fraudulent art]]!). Much
like any piece of art, if a piece on an NFT marketplace like [[https://mintbase.io/][Mintbase]], [[https://opensea.io/][OpenSea]],
or [[https://rarible.com/][Rarible]] catches your eye enough to warrant purchase, do some research about
the artist to verify the piece is non-fraudulent before buying. If you do
purchase an art NFT, virtual reality worlds like CryptoVoxels and Somnium Space
allow users to show off NFTs inside their virtual property (which of course, you
may purchase with an NFT).

It's worth taking a time-out to address one criticism of NFTs that seems
undeserved. [[http://cryptoart.wtf/][Environmentalist]] [[https://joanielemercier.com/the-problem-of-cryptoart/][critics]] have accused NFT artists consuming
excessive amounts of energy on Proof of Work chains. But as artist [[https://sterlingcrispin.blogspot.com/2021/02/crypto-art-sky-is-not-falling.html][Stirling
Crispin points out]] in an excellently researched essay, NFTs account for about [[https://etherscan.io/gastracker][3%]]
of gas consumption on Ethereum, which in turn uses 0.02% of the total Earth CO2
footprint. There are greater obstacles to energy neutrality than a small
community of talented people exploring ways to monetize their work:
#+begin_quote
The real problem is the giant 72%...it’s fossil fuel subsidies, its coal power
plants, its fracking. If your number one motivation is the environment, and
you’re behaving rationally, it makes sense to focus on the big things most and
the little things least.
#+end_quote

Further, NFT platforms are not married to Proof-of-Work blockchains. [[https://near.mintbase.io/][Mintbase]]
gives our users the tools to deploy their own NFT contracts. We opted to add
support for the Proof-of-Stake chain [[https://near.org/][NEAR]], so that our users may minimize their
transaction costs and environmental impact.

So we've got speculation, status, and support for art and artist communities. I
haven't exactly painted a glamorous picture of NFTs, so you'd be excused for the
suspicion that NFTs aren't actually that cool. But you'd be WRONG. Downstream
from the hype cycle, some great projects are taking form, with NFTs at their
core.

** Like what?
NFTs are a tool for collaboration and creation. The NFT might be best understood
as a [[https://en.wikipedia.org/wiki/Public-key_cryptography][Public Key]] for an item or service, on a public database. The departure from
a private database model allows for ease of collaboration, while guaranteeing
users to the longevity of their data.

Gaming NFTs, like [[https://zkga.me/][Dark Forest]], [[https://axieinfinity.com/][Axie Infinity]], and [[https://godsunchained.com/][Gods Unchained]] scratch the
surface of what's possible, by tokenizing in-game assets, which are easily
exchanged on on-chain marketplaces. Further, gaming NFTs can do more than one
thing. Imagine if after spending 100 hours grinding in World of Warcraft, the
Sword of Coolness item you earned gave you a rare playing card in Hearthstone, a
skin in Fortnite, and a ticket to a League of Legends esports event. Since NFTs
live on a public ledger, a single NFT can do as many things as there are
services willing to attach value to that NFT. Storing game data as an NFT,
thereby on a public database, is a departure from prior models, where all data
is stored privately. Private databases limit not only users' ability to access
and profit from their efforts and data but also limits opportunities for
cross-pollination between projects.

Beyond gaming application NFTs in the decades to come are likely to be a force
for standardizing an extensible concept of ownership. Extensible, as the base
concept of an NFT is [[http://erc721.org/][very simple]]. Simplicity that can be extended as the use
case demands, by way of extending the base contract, or else by attaching
services to the ownership of an NFT. Much like smartphones have simplified the
interface to communication, transportation, and social media, NFTs simplify the
interface to ownership of access to goods and services.

The NFT-maximal future doesn't have much in common with the NFT speculation
today, but for that goods and services that can be represented as NFTs will have
incentive to do so, so as to take advantage of ease of issuance, verification,
integration with other NFT-enabled businesses, and to reap royalty payments for
NFT transfers. Users will be able to view, manage, buy, and sell goods and
services across domains. Imagine if your gym membership, blog subscriptions,
rewards programs, event tickets, and more, could all be managed, bought, and
sold within a single application.

In place of the myriad interfaces we use daily to prove our right of access to
goods and services, from tickets to titles to coupons to login credentials, the
(1) public, uncensorable verifiability of NFTs, (2) ease of transfer of NFTs,
and (3) shared interface to each of these application areas mean that the realm
of possibilities of NFT-enabled technology is far-reaching.

** Wrap up
To recap. What are NFTs for? At the moment, speculation, status signalling, and
artwork are the ascendant NFT applications. But NFTs are [[https://threadreaderapp.com/thread/1365390455957950464.html][incredibly flexible]] as
technological tools, and could someday be for lots of things, or at least, much
more than what they're currently used for. Gaming applications are allowing
users to reap dividends from their play-time, by representing in-game assets as
NFTs. And an NFT future could involve much more (maybe after a hype cycle or
two).

The [[https://twitter.com/cryptograthor][author]] is a developer at Mintbase, a platform giving users an interface to
create and their own NFT minting contracts. We're on [[https://mintbase.io/][Ethereum]] and have recently
launched on [[https://near.mintbase.io/][NEAR testnet]]! If you're exploring what's possible with NFTs, check
us out.
